[project]
name = 'StormDrainChain-Infrastructure-Network'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.blockage-monitoring-system]
path = 'contracts/blockage-monitoring-system.clar'
clarity_version = 3
epoch = 'latest'

[contracts.storm-drain-registry]
path = 'contracts/storm-drain-registry.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
